# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'sh_test_spn'
    subscriptionId: 'caf16bab-b20f-449e-a538-7a1882ce6d37'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'vs-logaudit01'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/mahelsay/demo_alert_rules/main/alert_rules/azuredeploy.json'
    overrideParameters: '-projectName VS_SOC_IaC'
    deploymentMode: 'Incremental'
    deploymentName: 'sh_test'